
- name: instalando o puppetserver 
  package: 
   name: puppetserver
   state: present 
   update_cache: yes 
  when: ansible_hostname == "devops"


- name: instalando o puppet-agent
  package: 
   name: puppet-agent
   state: present  
   update_cache: yes 
