
- name: copiando o arquivo hosts para todas as maquinas
  copy: 
   src: "{{item.src}}"
   dest: "{{item.dest}}"
  with_items:
   - { src: files/hosts, dest: /etc/hosts }
   - { src: files/bash_rc, dest: /root/.bashrc } 

