- name: instalando o gitlab
  hosts: devops
  tasks:
   - name: adicionando o repositorio
     shell: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash" 
   
   - name: instalando dependencias 
     package:
      name: 
       - curl
       - openssh-server
       - ca-certificates 
       - postfix
       - gitlab-ce 
      state: present
      update_cache: yes 


